name: 'Terraform Preprod Deployment'

on:
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    if: contains(github.event.pull_request.labels.*.name, 'preprod')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ secrets.PREPROD_STATE_BUCKET_NAME }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_DB_USERNAME: ${{ secrets.TF_VAR_DB_USERNAME }}
        TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
        TF_VAR_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        TF_VAR_TECHRONOMICON_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        TF_VAR_TECHRONOMICON_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_TECHRONOMICON_STORAGE_BUCKET_NAME: ${{ secrets.PREPROD_TECHRONOMICON_STORAGE_BUCKET_NAME }}
        TF_VAR_TECHRONOMICON_RDS_DB_NAME: ${{ secrets.TECHRONOMICON_RDS_DB_NAME }}
        TF_VAR_STATE_BUCKET_NAME: ${{ secrets.PREPROD_STATE_BUCKET_NAME }}
        TF_VAR_ROUTE_53_RESOURCES_BOOL: ${{ secrets.PREPROD_ROUTE_53_RESOURCES_BOOL }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_DB_USERNAME: ${{ secrets.TF_VAR_DB_USERNAME }}
        TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
        TF_VAR_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        TF_VAR_TECHRONOMICON_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        TF_VAR_TECHRONOMICON_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_TECHRONOMICON_STORAGE_BUCKET_NAME: ${{ secrets.PREPROD_TECHRONOMICON_STORAGE_BUCKET_NAME }}
        TF_VAR_TECHRONOMICON_RDS_DB_NAME: ${{ secrets.TECHRONOMICON_RDS_DB_NAME }}
        TF_VAR_STATE_BUCKET_NAME: ${{ secrets.PREPROD_STATE_BUCKET_NAME }}
        TF_VAR_ROUTE_53_RESOURCES_BOOL: ${{ secrets.PREPROD_ROUTE_53_RESOURCES_BOOL }}

    - name: Get Preprod IP Address
      id: preprod_ip
      run: echo "::set-output name=ip_address::$(terraform output -raw instance_ip_address | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}

    - name: Get Public Key
      run: |
        KEY_RESPONSE=$(curl -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
                             -H "Accept: application/vnd.github.v3+json" \
                             https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
        echo "KEY_RESPONSE=$KEY_RESPONSE" > key_response.txt

    - name: Extract Key ID and Public Key
      run: |
        KEY_ID=$(grep '"key_id":' key_response.txt | cut -d ':' -f 2 | sed 's/"//g' | tr -d '[:space:]')
        PUBLIC_KEY=$(grep '"key":' key_response.txt | cut -d ':' -f 2 | sed 's/"//g' | tr -d '[:space:]')
        echo "KEY_ID=$KEY_ID" >> $GITHUB_ENV
        echo "PUBLIC_KEY=$PUBLIC_KEY" >> $GITHUB_ENV

    - name: Encrypt and Set Secret
      run: |
        echo -n "$PUBLIC_KEY" | base64 --decode > public_key.pem
        ENCRYPTED_VALUE=$(echo -n "${{ steps.preprod_ip.outputs.ip_address }}" | openssl pkeyutl -encrypt -pubin -inkey public_key.pem | base64)
        rm public_key.pem
        PAYLOAD="{\"encrypted_value\":\"$ENCRYPTED_VALUE\",\"key_id\":\"$KEY_ID\"}"
        curl -u "${{ github.actor }}:${{ secrets.ACTIONS_PAT }}" -X PUT -H "Content-Type: application/json" \
             -d "$PAYLOAD" "https://api.github.com/repos/${{ github.repository }}/actions/secrets/PREPROD_IP_ADDRESS"
