name: 'Terraform Preprod Deployment'

on:
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    if: contains(github.event.pull_request.labels.*.name, 'preprod')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ secrets.PREPROD_STATE_BUCKET_NAME }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_DB_USERNAME: ${{ secrets.TF_VAR_DB_USERNAME }}
        TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
        TF_VAR_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        TF_VAR_TECHRONOMICON_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        TF_VAR_TECHRONOMICON_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_TECHRONOMICON_STORAGE_BUCKET_NAME: ${{ secrets.PREPROD_TECHRONOMICON_STORAGE_BUCKET_NAME }}
        TF_VAR_TECHRONOMICON_RDS_DB_NAME: ${{ secrets.TECHRONOMICON_RDS_DB_NAME }}
        TF_VAR_STATE_BUCKET_NAME: ${{ secrets.PREPROD_STATE_BUCKET_NAME }}
        TF_VAR_ROUTE_53_RESOURCES_BOOL: ${{ secrets.PREPROD_ROUTE_53_RESOURCES_BOOL }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_DB_USERNAME: ${{ secrets.TF_VAR_DB_USERNAME }}
        TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
        TF_VAR_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        TF_VAR_TECHRONOMICON_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        TF_VAR_TECHRONOMICON_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
        TF_VAR_TECHRONOMICON_STORAGE_BUCKET_NAME: ${{ secrets.PREPROD_TECHRONOMICON_STORAGE_BUCKET_NAME }}
        TF_VAR_TECHRONOMICON_RDS_DB_NAME: ${{ secrets.TECHRONOMICON_RDS_DB_NAME }}
        TF_VAR_STATE_BUCKET_NAME: ${{ secrets.PREPROD_STATE_BUCKET_NAME }}
        TF_VAR_ROUTE_53_RESOURCES_BOOL: ${{ secrets.PREPROD_ROUTE_53_RESOURCES_BOOL }}

    - name: Get Preprod IP Address
      id: preprod_ip
      run: echo "::set-output name=ip_address::$(terraform output -raw instance_ip_address | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}

    - name: Set Action Secret
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'PREPROD_IP_ADDRESS'
        value: ${{ steps.preprod_ip.outputs.ip_address }}
        repository: ${{ github.repository }}
        token: ${{ secrets.ACTIONS_PAT }}
