name: Transfer Secrets to Preprod Environment

on:
  workflow_dispatch:

jobs:
  transfer-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Transfer Secrets
        env:
          GH_PAT: ${{ secrets.ACTIONS_PAT }}
          REPO: lukejcollins/techronomicon
          ENVIRONMENT: preprod
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          PREPROD_AWS_ACCESS_KEY_ID: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          PREPROD_AWS_REGION: ${{ secrets.PREPROD_AWS_REGION }}
          PREPROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          PREPROD_ECS_CLUSTER_NAME: ${{ secrets.PREPROD_ECS_CLUSTER_NAME }}
          PREPROD_ECS_SERVICE_NAME: ${{ secrets.PREPROD_ECS_SERVICE_NAME }}
          PREPROD_TECHRONOMICON_STORAGE_BUCKET_NAME: ${{ secrets.PREPROD_TECHRONOMICON_STORAGE_BUCKET_NAME }}
        run: |
          declare -A SECRETS=(
            ["DJANGO_SECRET_KEY"]=$DJANGO_SECRET_KEY
            ["AWS_ACCESS_KEY_ID"]=$PREPROD_AWS_ACCESS_KEY_ID
            ["AWS_REGION"]=$PREPROD_AWS_REGION
            ["AWS_SECRET_ACCESS_KEY"]=$PREPROD_AWS_SECRET_ACCESS_KEY
            ["ECS_CLUSTER_NAME"]=$PREPROD_ECS_CLUSTER_NAME
            ["ECS_SERVICE_NAME"]=$PREPROD_ECS_SERVICE_NAME
            ["TECHRONOMICON_STORAGE_BUCKET_NAME"]=$PREPROD_TECHRONOMICON_STORAGE_BUCKET_NAME
          )
          
          for secret_key in "${!SECRETS[@]}"; do
            secret_value=${SECRETS[$secret_key]}
            curl -X PUT -H "Authorization: token $GH_PAT" \
              -H "Content-Type: application/json" \
              https://api.github.com/repos/$REPO/environments/$ENVIRONMENT/secrets/$secret_key \
              -d "$(jq -n --arg secret_value "$secret_value" '{encrypted_value: $secret_value}')"
          done
